<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #0174DF;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
        a{
            color: #610B4B;
        }
    </style>
</head>
<body style="background-color: #E6E6E6;">
    <div id="wrapper">
        <h1>Test Metrica Andina</h1>
        <div>Problema Practico</div>
        <legend></legend>
        <div class="container-fluid">
            <div class="row">
              <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">  </div>
              <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12"><a href="../public/employee">List of employees</a> ||
              <a href="../public/salary?minimo=1500&maximo=2000"> XML Service</a> </div>                  
              </div>
          </div>
      </div>
  </body>
  </html>
